### ISSUE TITLE
Windowsでテストが動かない

### ISSUE THREAD

**Issue by sera1mu** [sera1mu/deno-mecab#3]
v1.0.0リリース前、GitHub Actionsの `windows-latest` で実行しようとしたところ、次のようなエラーでテストに失敗しました。
手元にWindowsPCがなくて原因わかっていません。

```
running 8 tests from file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts
test MeCab: generateMeCabRunError ... ok (7ms)
test MeCab: parse ... FAILED (12ms)
test MeCab: dump ... FAILED (8ms)
test MeCab: chasen (not included spaces) ... FAILED (9ms)
test MeCab: chasen (include spaces) ... FAILED (7ms)
test MeCab: simple ... FAILED (8ms)
test MeCab: wakati ... FAILED (8ms)
test MeCab: yomi ... FAILED (8ms)

failures:

MeCab: parse
Error: Failed to run MeCab correctly: Error: %1 is not a valid Win32 application. (os error 193)
    at Function.generateMeCabRunError (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:25:12)
    at MeCab.parse (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:78:19)
    at async file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts:26:18
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
error: Test failed
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:283:22)
    at async file:///D:/a/deno-mecab/deno-mecab/e74ab1ea-1b90-48fb-9135-043ea70532a3$deno$test.js:4:7

MeCab: dump
Error: Failed to run MeCab correctly: %1 is not a valid Win32 application. (os error 193)
    at Function.generateMeCabRunError (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:25:12)
    at MeCab.dump (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:102:19)
    at async file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts:35:18
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:283:22)
    at async file:///D:/a/deno-mecab/deno-mecab/e74ab1ea-1b90-48fb-9135-043ea70532a3$deno$test.js:4:7

MeCab: chasen (not included spaces)
Error: Failed to run MeCab correctly: %1 is not a valid Win32 application. (os error 193)
    at Function.generateMeCabRunError (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:25:12)
    at MeCab.chasen (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:135:19)
    at async file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts:44:18
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:283:22)
    at async file:///D:/a/deno-mecab/deno-mecab/e74ab1ea-1b90-48fb-9135-043ea70532a3$deno$test.js:4:7

MeCab: chasen (include spaces)
Error: Failed to run MeCab correctly: %1 is not a valid Win32 application. (os error 193)
    at Function.generateMeCabRunError (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:25:12)
    at MeCab.chasen (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:135:19)
    at async file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts:53:18
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:283:22)
    at async file:///D:/a/deno-mecab/deno-mecab/e74ab1ea-1b90-48fb-9135-043ea70532a3$deno$test.js:4:7

MeCab: simple
Error: Failed to run MeCab correctly: %1 is not a valid Win32 application. (os error 193)
    at Function.generateMeCabRunError (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:25:12)
    at MeCab.simple (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:159:19)
    at async file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts:62:18
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:283:22)
    at async file:///D:/a/deno-mecab/deno-mecab/e74ab1ea-1b90-48fb-9135-043ea70532a3$deno$test.js:4:7

MeCab: wakati
Error: Failed to run MeCab correctly: %1 is not a valid Win32 application. (os error 193)
    at Function.generateMeCabRunError (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:25:12)
    at MeCab.wakati (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:183:19)
    at async file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts:71:18
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:283:22)
    at async file:///D:/a/deno-mecab/deno-mecab/e74ab1ea-1b90-48fb-9135-043ea70532a3$deno$test.js:4:7

MeCab: yomi
Error: Failed to run MeCab correctly: %1 is not a valid Win32 application. (os error 193)
    at Function.generateMeCabRunError (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:25:12)
    at MeCab.yomi (file:///D:/a/deno-mecab/deno-mecab/MeCab.ts:202:19)
    at async file:///D:/a/deno-mecab/deno-mecab/test/MeCab.test.ts:80:18
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:283:22)
    at async file:///D:/a/deno-mecab/deno-mecab/e74ab1ea-1b90-48fb-9135-043ea70532a3$deno$test.js:4:7

failures:

	MeCab: parse
	MeCab: dump
	MeCab: chasen (not included spaces)
	MeCab: chasen (include spaces)
	MeCab: simple
	MeCab: wakati
	MeCab: yomi

test result: FAILED. 1 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out (124ms)

Error: Process completed with exit code 1.
```

**Comment by manzyun** [comment]
Denoの `rusty_v8` のWindowsビルドかと思ってたら、こういう事でしたのね。あるある。

https://github.com/sera1mu/deno-mecab/commit/4ef908ec92e423f6a4a71c8969e3d530ad23f182

**Comment by sera1mu** [comment]
@manzyun 氏の協力で解決しました。
原因はテストコードにありました。

Unix系だと単に `./dummyMeCab.ts` と実行しても、ファイルにshebangがあるのでDenoで実行してくれます。
しかしWindowsだと、単に実行しても「実行可能ファイル」として認識されず、エラーが発生していました。
これを解決するため、`./dummyMeCab.sh` と実行するのではなく `deno run dummyMeCab.ts` と実行するようにしました。

つまり、原因はソースコードそのものではなく、テストコードにありました。
「Windowsで動かない」ではなく「Windowsで _テストコードが_ 動かない」ということでした。

この問題は 4ef908ec92e423f6a4a71c8969e3d530ad23f182 において解決されました。そのため、このIssueをクローズします。
なお、このあとすぐに情報を書き改めた v1.0.1をリリースする予定です。
